version: '3'

networks:
  node-network:
    driver: bridge

services:
  node:
    build: ./node
    image: rruffer/node-app
    container_name: node-app
    networks:
      - node-network
    depends_on: # https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.30
    container_name: node-db
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --lower_case_table_names=1
    healthcheck:
      test: "mysql -uroot -proot --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - node-network
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx-server
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
    depends_on:
      - node
    environment:
      - TZ=America/Sao_Paulo
